services:
  - type: web
    name: bys-dependientes
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_PATH
        value: /app/public-frontend
